### ISSUE TITLE
Doesn't insert on PUT [optional req]

### ISSUE THREAD

**Issue by citizenrich** [jembi/hearth#118]
This line prevents the insertion of a new resource using PUT.
https://github.com/jembi/hearth/blob/d1a0d34ce0f7051a2c3897b6bd801b46d0a9fe63/lib/fhir/core.js#L433

In order to retain the existing ID for a resource, it must be inserted via PUT (not POST) with the ID. I'm curious if there's an appetite to change that?

**Comment by rcrichton** [comment]
Hi @citizenrich, we have had discussions about whether to make this change or not before but haven't quite landed on a answer for whether this would be a correct use of FHIR or not.

The argument against is that a FHIR server should really manage it's own IDs (which is essentially its primary keys) and that should be irrelevant to an outside system. The server cannot guarantee that there won't be clashes with other IDs if it accepts IDs that the user sends.

The argument for is that it makes it easier for FHIR servers and clients to use IDs that they already have been using, thus making integration easier.

I'd be keen to hear your thoughts on this and a usecase for why this would be useful for you.

What we could do is make this an option in config to allow upserts which defaults to false. That may make both sides happy.

**Comment by citizenrich** [comment]
Thanks @rcrichton the config option would be great. The use case is that we are moving data from one FHIR source to Hearth. We'd like to keep all of the existing mappings in place.

**Comment by citizenrich** [comment]
Just a ping on this issue in the hope that it goes on a roadmap.

**Comment by BMartinos** [comment]
This is being addresses in PR https://github.com/jembi/hearth/pull/164

**Comment by rowanpi** [comment]
I am closing this issue as it has been resolved in the PR @BMartinos referred to.
